import streamlit as st
from pptx import Presentation
import io
import json
from groq import Groq

# --- Page Configuration ---
st.set_page_config(
    page_title="AI Presentation Architect",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Dynamic Model Fetching ---
@st.cache_data(ttl=3600) # Cache the model list for 1 hour
def get_available_groq_models(_client):
    """
    Fetches available, active LLM models directly from the Groq API.
    """
    try:
        model_list = _client.models.list().data
        active_models = [m for m in model_list if m.active and "embedding" not in m.id]
        return sorted([model.id for model in active_models])
    except Exception as e:
        st.warning(f"Could not fetch live model list from Groq. Using a fallback list. Error: {e}")
        return ["llama3-70b-8192", "llama3-8b-8192", "mixtral-8x7b-32768", "gemma2-9b-it"]

# --- Core Presentation Logic (with True Templating Fix) ---
def create_presentation_from_template(template_file, title, content_bullets):
    """
    Creates a new presentation by using the uploaded file as a true template.
    It deletes all existing slides and then adds new ones based on the template's layouts.
    """
    try:
        # Load the uploaded presentation file
        prs = Presentation(template_file)
    except Exception as e:
        st.error(f"❌ Error reading the template file: {e}")
        return None

    # --- CRUCIAL FIX: Delete all existing slides ---
    # This leaves the presentation empty but preserves all master layouts and themes.
    try:
        # Create a list of slide IDs to remove, as iterating and removing is unsafe
        slide_ids_to_remove = [slide.rId for slide in prs.slides]
        for rId in slide_ids_to_remove:
            prs.part.drop_rel(rId)
        # Clear the internal list of slides
        prs.slides._sldIdLst.clear()
    except Exception as e:
        st.error(f"❌ Could not clean the template file. Error: {e}")
        return None
    # --- END OF CRUCIAL FIX ---

    # Add New Title Slide (using Layout 0 from the template)
    if len(prs.slide_layouts) > 0:
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        if slide.shapes.title: slide.shapes.title.text = title
        try: slide.placeholders[1].text = "Generated by AI Presentation Architect"
        except (KeyError, IndexError): pass # Fails gracefully if no subtitle placeholder
    else:
        st.warning("⚠️ Your template must have at least one slide layout."); return None

    # Add New Content Slide (using Layout 1 from the template)
    if len(prs.slide_layouts) > 1:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        if slide.shapes.title: slide.shapes.title.text = "Key Discussion Points"
        try:
            body_shape = slide.placeholders[1]; tf = body_shape.text_frame; tf.clear()
            for bullet in content_bullets: p = tf.add_paragraph(); p.text = bullet; p.level = 0
        except (KeyError, IndexError): st.warning("⚠️ Your template's content layout is non-standard.")
    else:
        st.error("❌ Your template needs at least two layouts (Title, Content)."); return None

    bio = io.BytesIO(); prs.save(bio); bio.seek(0); return bio

# --- Groq LLM Content Generation ---
def generate_content_with_groq(api_key, model, prompt):
    if not api_key: st.error("Groq API key not configured in Streamlit secrets."); return ""
    client = Groq(api_key=api_key)
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are an assistant for generating concise, impactful bullet points for business presentations. Do not include a title or summary. Each bullet point must start on a new line."},
                {"role": "user", "content": prompt}
            ], model=model
        )
        return chat_completion.choices[0].message.content
    except Exception as e: st.error(f"Groq API Error: {e}"); return ""

# --- UI Initialization and State ---
st.title("🚀 AI Presentation Architect")
st.markdown("Instantly create enterprise-level presentations using a live list of AI models.")
if 'generated_content' not in st.session_state: st.session_state.generated_content = "The Power of AI in business automation.\nLeveraging machine learning for predictive insights."
if 'show_preview' not in st.session_state: st.session_state.show_preview = False
if 'ppt_download_buffer' not in st.session_state: st.session_state.ppt_download_buffer = None

# --- UI Sidebar ---
with st.sidebar:
    st.header("⚙️ Configuration")
    with st.expander("1️⃣ Upload Template", expanded=True):
        uploaded_template = st.file_uploader("Upload a .pptx file", type="pptx", label_visibility="collapsed")
    with st.expander("2️⃣ Define Content", expanded=True):
        presentation_title = st.text_input("Presentation Title", "Quarterly Business Review")
        if st.toggle("Generate Content with AI", value=True):
            st.subheader("AI Content Engine")
            try:
                groq_api_key = st.secrets["GROQ_API_KEY"]; groq_client = Groq(api_key=groq_api_key)
                st.success("Groq API key loaded.", icon="✅")
            except:
                st.error("Groq API key not found in secrets."); groq_api_key = None; groq_client = None
            if groq_client:
                available_models = get_available_groq_models(groq_client)
                selected_model_id = st.selectbox("Select AI Model (Live from Groq)", options=available_models)
                ai_prompt = st.text_area("Your Prompt", "Create 5 bullet points on the future of renewable energy.", height=150)
                if st.button("✨ Generate Content"):
                    with st.spinner(f"🤖 Calling {selected_model_id}..."):
                        generated_text = generate_content_with_groq(groq_api_key, selected_model_id, ai_prompt)
                        if generated_text:
                            st.session_state.generated_content = generated_text; st.session_state.show_preview = False
                            st.session_state.ppt_download_buffer = None; st.toast("Content generated!", icon="🎉"); st.rerun()
            else: st.info("Configure your Groq API key to see the model list.")
    st.divider()
    st.subheader("📝 Review & Edit Content")
    content_text = st.text_area("Content (one bullet per line)", value=st.session_state.generated_content, height=250, label_visibility="collapsed")

# --- UI Main Area ---
if not uploaded_template:
    st.info("👈 Please upload your company's .pptx template to begin.")
else:
    if st.session_state.ppt_download_buffer:
        st.success("✅ Your presentation is ready to download!")
        st.download_button(
            label="📥 Download Presentation (.pptx)", data=st.session_state.ppt_download_buffer,
            file_name=f"{st.session_state.get('presentation_title', 'presentation').replace(' ', '_').lower()}.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation", use_container_width=True
        )
        st.markdown("---")
    st.header("🎬 Preview and Generate")
    content_bullets = [line.strip() for line in content_text.split('\n') if line.strip()]
    if not st.session_state.show_preview:
        if st.button("📝 Preview My Presentation", use_container_width=True):
            if not presentation_title or not content_bullets: st.warning("Please provide a title and bullet points.")
            else: st.session_state.show_preview = True; st.session_state.ppt_download_buffer = None; st.rerun()
    if st.session_state.show_preview:
        st.subheader("Content Preview")
        with st.container(border=True):
            st.markdown(f"##### Slide 1: Title Slide\n- **Title:** `{presentation_title}`")
            st.markdown("---")
            st.markdown(f"##### Slide 2: Content Slide\n- **Title:** `Key Discussion Points`")
            for bullet in content_bullets: st.markdown(f"  - {bullet}")
        st.divider()
        if st.button("✅ Confirm & Generate PPT", type="primary", use_container_width=True):
            with st.spinner("Assembling your presentation..."):
                generated_ppt_io = create_presentation_from_template(uploaded_template, presentation_title, content_bullets)
                if generated_ppt_io:
                    st.session_state.presentation_title = presentation_title
                    st.session_state.ppt_download_buffer = generated_ppt_io
                    st.session_state.show_preview = False
                    st.rerun()
