import streamlit as st
from pptx import Presentation
import io
import json
from groq import Groq

# --- Page Configuration ---
st.set_page_config(
    page_title="AI Presentation Architect",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Core Presentation Logic ---
def create_presentation_from_template(template_file, title, content_bullets):
    """
    Creates a new presentation from a template, with robust checks for missing placeholders.
    """
    try:
        prs = Presentation(template_file)
    except Exception as e:
        st.error(f"❌ Error reading the template file: {e}")
        return None

    # Add Title Slide (Layout 0)
    if len(prs.slide_layouts) > 0:
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        if slide.shapes.title:
            slide.shapes.title.text = title
        try:
            slide.placeholders[1].text = "Generated by AI Presentation Architect"
        except KeyError:
            pass  # No subtitle placeholder, which is fine.
    else:
        st.warning("⚠️ Your template must have at least one slide layout.")
        return None

    # Add Content Slide (Layout 1)
    if len(prs.slide_layouts) > 1:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        if slide.shapes.title:
            slide.shapes.title.text = "Key Discussion Points"
        try:
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()
            for bullet in content_bullets:
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 0
        except KeyError:
            st.warning("⚠️ Your template's content layout is non-standard. Could not add bullet points.")
    else:
        st.error("❌ Your template needs at least two layouts (Title, Content).")
        return None

    bio = io.BytesIO()
    prs.save(bio)
    bio.seek(0)
    return bio

# --- Groq LLM Content Generation ---
def generate_content_with_groq(api_key, model, prompt):
    """
    Generates content using Groq API and provides user-friendly error messages.
    """
    if not api_key:
        st.error("Groq API key not configured in Streamlit secrets.")
        return ""
    
    client = Groq(api_key=api_key)
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are a world-class assistant for generating concise, impactful bullet points for business presentations. Do not include a title, introduction, or summary. Each bullet point must start on a new line."},
                {"role": "user", "content": prompt}
            ],
            model=model
        )
        return chat_completion.choices[0].message.content
    except Exception as e:
        try:
            error_json_str = str(e).split(' - ', 1)[1]
            error_data = json.loads(error_json_str.replace("'", "\""))
            message = error_data.get('error', {}).get('message', 'An unknown API error occurred.')
            st.error(f"Groq API Error: {message}")
        except:
            st.error(f"An unexpected error occurred with the Groq API: {e}")
        return ""

# --- UI Initialization ---
st.title("🚀 AI Presentation Architect")
st.markdown("Instantly create enterprise-level presentations. Upload your template, generate AI content, preview, and download.")

if 'generated_content' not in st.session_state:
    st.session_state['generated_content'] = "The Power of AI in business automation.\nLeveraging machine learning for predictive insights."
if 'show_preview' not in st.session_state:
    st.session_state['show_preview'] = False

# --- UI: Sidebar ---
with st.sidebar:
    st.header("⚙️ Configuration")

    with st.expander("1️⃣ Upload Template", expanded=True):
        uploaded_template = st.file_uploader("Upload a .pptx file", type="pptx", label_visibility="collapsed")

    with st.expander("2️⃣ Define Content", expanded=True):
        presentation_title = st.text_input("Presentation Title", "Quarterly Business Review")
        
        if st.toggle("Generate Content with AI", value=True):
            st.subheader("AI Content Engine")
            try:
                groq_api_key = st.secrets["GROQ_API_KEY"]
                st.success("Groq API key loaded securely.", icon="✅")
            except (FileNotFoundError, KeyError):
                st.error("Groq API key not found in secrets.")
                groq_api_key = None

            # --- FINAL CORRECTED MODEL LIST ---
            available_models = {
                "Llama 3 (70b)": "llama3-70b-8192",
                "Llama 3 (8b)": "llama3-8b-8192",
                "Mixtral (8x7b)": "mixtral-8x7b-32768",
                "Gemma 2 (9b)": "gemma2-9b-it",
            }
            # --- END OF CORRECTION ---

            selected_model_name = st.selectbox("Select AI Model", options=list(available_models.keys()))
            selected_model_id = available_models[selected_model_name]
            ai_prompt = st.text_area("Your Prompt", "Create 5 bullet points on the future of renewable energy.", height=150)
            
            if st.button("✨ Generate Content"):
                if groq_api_key:
                    with st.spinner(f"🤖 Calling {selected_model_name}..."):
                        generated_text = generate_content_with_groq(groq_api_key, selected_model_id, ai_prompt)
                        if generated_text:
                            st.session_state['generated_content'] = generated_text
                            st.toast("Content generated!", icon="🎉")
                            st.session_state.show_preview = False
                            st.rerun()

    st.divider()
    st.subheader("📝 Review & Edit Content")
    content_text = st.text_area("Content (one bullet per line)", value=st.session_state['generated_content'], height=250, label_visibility="collapsed")

# --- UI: Main Area ---
if uploaded_template is not None:
    st.header("🎬 Preview and Generate")
    
    content_bullets = [line.strip() for line in content_text.split('\n') if line.strip()]

    if not st.session_state.show_preview:
        if st.button("📝 Preview My Presentation", use_container_width=True):
            if not presentation_title or not content_bullets:
                st.warning("Please provide a title and at least one bullet point.")
            else:
                st.session_state.show_preview = True
                st.rerun()

    if st.session_state.show_preview:
        st.subheader("Content Preview")
        with st.container(border=True):
            st.markdown(f"##### Slide 1: Title Slide\n- **Title:** `{presentation_title}`\n- **Subtitle:** `Generated by AI Presentation Architect`")
            st.markdown("---")
            st.markdown(f"##### Slide 2: Content Slide\n- **Title:** `Key Discussion Points`\n- **Body:**")
            for bullet in content_bullets:
                st.markdown(f"  - {bullet}")
        
        st.divider()
        
        if st.button("✅ Confirm & Generate PPT", type="primary", use_container_width=True):
            with st.spinner("Assembling your presentation..."):
                generated_ppt_io = create_presentation_from_template(uploaded_template, presentation_title, content_bullets)
                if generated_ppt_io:
                    st.success("Presentation generated successfully!")
                    st.download_button(
                        label="📥 Download Presentation (.pptx)",
                        data=generated_ppt_io,
                        file_name=f"{presentation_title.replace(' ', '_').lower()}.pptx",
                        mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                        use_container_width=True
                    )
                    st.session_state.show_preview = False
                    st.rerun()
else:
    st.info("👈 Please upload your company's .pptx template in the sidebar to begin.")
