import streamlit as st
from pptx import Presentation
from pptx.enum.shapes import PP_PLACEHOLDER
import io
import json
from groq import Groq

# --- Page Configuration ---
st.set_page_config(
    page_title="AI Presentation Architect",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Dynamic Model Fetching ---
@st.cache_data(ttl=3600)
def get_available_groq_models(_client):
    try:
        model_list = _client.models.list().data
        active_models = [m for m in model_list if m.active and "embedding" not in m.id]
        return sorted([model.id for model in active_models])
    except Exception as e:
        st.warning(f"Could not fetch live model list. Using fallback. Error: {e}")
        return ["llama3-8b-8192", "mixtral-8x7b-32768", "gemma2-9b-it"]

# --- Core Presentation Logic (with Intelligent Layout Detection) ---
def create_presentation_from_template(template_file, main_title, slides_content):
    """
    Creates a new presentation by intelligently analyzing the template, using only
    appropriate layouts for title and content slides.
    """
    try:
        prs = Presentation(template_file)
    except Exception as e:
        st.error(f"❌ Error reading the template file: {e}"); return None

    # --- Intelligent Layout Discovery ---
    title_layout = None
    content_layouts = []

    for layout in prs.slide_layouts:
        has_title = any(p.placeholder_format.type in [PP_PLACEHOLDER.TITLE, PP_PLACEHOLDER.CENTER_TITLE] for p in layout.placeholders)
        has_body = any(p.placeholder_format.type == PP_PLACEHOLDER.BODY for p in layout.placeholders)

        # The first layout with a title is likely the main title slide.
        if has_title and not title_layout:
            title_layout = layout
        
        # A valid content layout MUST have both a title and a body. This filters out section headers, etc.
        if has_title and has_body:
            content_layouts.append(layout)
    
    if not title_layout: title_layout = prs.slide_layouts[0] if len(prs.slide_layouts) > 0 else None
    if not content_layouts:
        st.error("❌ Template Error: Could not find any suitable 'Title and Content' layouts in your presentation. Please use a template with layouts that have both a title and a main body text area.")
        return None

    # --- Clean the presentation by removing all existing slides ---
    try:
        for i in range(len(prs.slides) - 1, -1, -1):
            rId = prs.slides._sldIdLst[i].rId
            prs.part.drop_rel(rId)
            del prs.slides._sldIdLst[i]
    except Exception as e:
        st.error(f"❌ Could not clean the template file. Error: {e}"); return None

    # --- Build the new presentation ---
    # Add Main Title Slide
    if not title_layout: st.warning("⚠️ Could not find a suitable title slide layout."); return None
    slide = prs.slides.add_slide(title_layout)
    if slide.shapes.title: slide.shapes.title.text = main_title
    try: slide.placeholders[1].text = "Generated by AI Presentation Architect"
    except (KeyError, IndexError): pass

    # Add Content Slides, cycling through the filtered list of valid layouts
    for i, content in enumerate(slides_content):
        layout = content_layouts[i % len(content_layouts)]
        slide = prs.slides.add_slide(layout)
        
        if slide.shapes.title: slide.shapes.title.text = content.get("title", "No Title")
        body_shape = next((shape for shape in slide.placeholders if shape.placeholder_format.type == PP_PLACEHOLDER.BODY), None)
        
        if body_shape:
            tf = body_shape.text_frame; tf.clear(); tf.word_wrap = True
            content_bullets = content.get("bullets", [])
            if content_bullets:
                try: p = tf.paragraphs[0]; p.text = content_bullets[0]
                except IndexError: p = tf.add_paragraph(); p.text = content_bullets[0]
                p.level = 0
                for bullet_text in content_bullets[1:]:
                    p = tf.add_paragraph(); p.text = bullet_text; p.level = 0
        else: st.warning(f"⚠️ Could not find 'Body' placeholder on Slide {i+2} using layout '{layout.name}'.")

    bio = io.BytesIO(); prs.save(bio); bio.seek(0); return bio

# --- Groq LLM Content Generation (JSON mode) ---
def generate_content_with_groq(api_key, model, topic, num_slides):
    # ... (This function remains robust and unchanged) ...
    if not api_key: st.error("Groq API key not configured."); return None
    client = Groq(api_key=api_key)
    system_prompt = f"""You are an expert presentation creator. Your response MUST be a valid JSON array of objects. Each object represents a single slide and must have two keys: "title" (a string) and "bullets" (an array of strings). Generate exactly {num_slides} unique slides about the topic: '{topic}'."""
    try:
        chat_completion = client.chat.completions.create(
            messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": f"Generate {num_slides} slides about {topic}."}],
            model=model, temperature=0.7, response_format={"type": "json_object"},
        )
        response_data = json.loads(chat_completion.choices[0].message.content)
        for key, value in response_data.items():
            if isinstance(value, list): return value
        st.error("AI did not return the expected slide array format."); return None
    except Exception as e: st.error(f"Groq API Error: {e}"); return None

# --- UI (No changes needed) ---
st.title("🚀 AI Presentation Architect")
st.markdown("Create multi-slide presentations with layout variety and editable content.")

# State Init
if 'generated_slides' not in st.session_state: st.session_state.generated_slides = []
if 'ppt_download_buffer' not in st.session_state: st.session_state.ppt_download_buffer = None

with st.sidebar:
    st.header("⚙️ Configuration")
    with st.expander("1️⃣ Upload Template", expanded=True):
        uploaded_template = st.file_uploader("Upload a .pptx file", type="pptx", label_visibility="collapsed")
    with st.expander("2️⃣ Define Content", expanded=True):
        presentation_title = st.text_input("Main Presentation Title", "Quarterly Business Review")
        st.subheader("AI Content Engine")
        try:
            groq_api_key = st.secrets["GROQ_API_KEY"]; groq_client = Groq(api_key=groq_api_key)
            st.success("Groq API key loaded.", icon="✅")
        except:
            st.error("Groq API key not found in secrets."); groq_api_key = None; groq_client = None

        if groq_client:
            available_models = get_available_groq_models(groq_client)
            selected_model_id = st.selectbox("Select AI Model (Live)", options=available_models)
            topic = st.text_input("Presentation Topic", "The Future of Renewable Energy")
            num_slides = st.number_input("Number of Content Slides", min_value=1, max_value=50, value=3)

            if st.button("✨ Generate Content"):
                with st.spinner(f"🤖 Calling {selected_model_id}..."):
                    generated_data = generate_content_with_groq(groq_api_key, selected_model_id, topic, num_slides)
                    if generated_data:
                        st.session_state.generated_slides = generated_data
                        st.session_state.ppt_download_buffer = None
                        st.toast(f"{len(generated_data)} slides generated!", icon="🎉"); st.rerun()

if not uploaded_template:
    st.info("👈 Please upload your company's .pptx template to begin.")
else:
    if st.session_state.ppt_download_buffer:
        st.success("✅ Your presentation is ready to download!")
        st.download_button(
            label="📥 Download Presentation (.pptx)", data=st.session_state.ppt_download_buffer,
            file_name=f"{st.session_state.get('presentation_title', 'presentation').replace(' ', '_').lower()}.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation", use_container_width=True
        )
        st.markdown("---")

    if st.session_state.generated_slides:
        st.header("📝 Edit & Generate Presentation")
        edited_slides = []
        with st.container(border=True):
            st.markdown(f"##### Main Title Slide\n- **Title:** `{presentation_title}`")
            st.markdown("---")
            for i, slide_content in enumerate(st.session_state.generated_slides, 1):
                with st.expander(f"Edit Content Slide {i}: {slide_content.get('title', 'N/A')}", expanded=True):
                    edited_title = st.text_input("Slide Title", value=slide_content.get("title"), key=f"title_{i}")
                    edited_bullets_text = st.text_area("Bullet Points", value="\n".join(slide_content.get("bullets", [])), key=f"bullets_{i}", height=150)
                edited_slides.append({"title": edited_title, "bullets": [line.strip() for line in edited_bullets_text.split("\n") if line.strip()]})
                st.markdown("---")
        st.divider()
        if st.button("✅ Confirm & Generate PPT", type="primary", use_container_width=True):
            with st.spinner("Assembling your presentation..."):
                generated_ppt_io = create_presentation_from_template(uploaded_template, presentation_title, edited_slides)
                if generated_ppt_io:
                    st.session_state.presentation_title = presentation_title
                    st.session_state.ppt_download_buffer = generated_ppt_io
                    st.session_state.generated_slides = []
                    st.rerun()
